AWSTemplateFormatVersion: 2010-09-09
Resources:
  Tweetbrief:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: Tweetbrief
      Handler: runner.lambda_handler
      Role: !GetAtt TweetbriefRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            pass
      Runtime: python3.6
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          CONSUMER_KEY: !Ref ConsumerKey
          CONSUMER_SECRET: !Ref ConsumerSecret
          DROPBOX_ACCESS_TOKEN: !Ref DropboxAccessToken
          TARGET_USERNAME: !Ref TargetUsername
          BRIEF_PERIOD: !Ref BriefPeriod
          BRIEF_MAX_TWEETS: !Ref BriefMaxTweets
          SINGLE_AUTHOR_MAX_TWEETS: !Ref SingleAuthorMaxTweets
          URL2QR: !Ref URL2QR
  TweetbriefRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TweetbriefRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AWSLambdaBasicExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: logs:*
                Resource: arn:aws:logs:*:*:*
  TweetbriefSchedule:
    Type: AWS::Events::Rule
    Properties:
      Name: TweetbriefSchedule
      ScheduleExpression: !Sub cron(0 0 */${BriefPeriod} * ? *)
      Targets:
        - Id: TweetbriefScheduleTarget
          Arn:
            Fn::GetAtt:
              - Tweetbrief
              - Arn
      State: ENABLED
  TweetbriefInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Tweetbrief
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - TweetbriefSchedule
          - Arn
Parameters:
  ConsumerKey:
    Type: String
    Description: An authentication key to query Twitter API.
  ConsumerSecret:
    Type: String
    Description: An authentication secret to query Twitter API.
  DropboxAccessToken:
    Type: String
    Description: An access token to save briefs on Dropbox.
  TargetUsername:
    Type: String
    Description: A target Twitter account. 
  BriefPeriod:
    Type: Number
    Description: The period of time, in days (24h), defining the window time of which tweets to gather.
    Default: 1
    MinValue: 1
  BriefMaxTweets:
    Type: Number
    Description: The maximum number of tweets to include in a brief.
    Default: 32
    MinValue: 1
  SingleAuthorMaxTweets:
    Type: Number
    Description: The maximum number of tweets from one user to include.
    Default: 3
    MinValue: 1
    MaxValue: 3
  URL2QR:
    Type: String
    Description: The flag indicating whether URLs should be converted to QR codes.
    Default: "True"
    AllowedValues:
      - "True"
      - "False"