name: CI/CD
on:
  push:
    branches:
      - feature/aws-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv lock --requirements > requirements.txt
          python -m pip install -r requirements.txt --target dependencies
      
      - name: Zip dependencies
        run: |
          cd dependencies
          zip  -r ../dependencies.zip *
          cd ..
      
      - name: Zip function
        env:
          SOURCE_DIR: tweetbrief
        run: |
          cd "${SOURCE_DIR}"
          zip -r ../function.zip *
          cd ..
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Publish dependencies layer to AWS Lambda
        env: 
          AWS_LAMBDA_LAYER_ARN: arn:aws:lambda:eu-north-1:807414917081:layer:dependencies
        run: |
          RESULT=$(aws lambda publish-layer-version --layer-name "${AWS_LAMBDA_LAYER_ARN}" --zip-file fileb://dependencies.zip)
          LAYER_VERSION=$(jq '.Version' <<< "${RESULT}")
          echo "::set-env name=LAYER_VERSION::$LAYER_VERSION"
    
      - name: Publish function layer to AWS Lambda
        env:
          AWS_LAMBDA_FUNCTION_NAME: arn:aws:lambda:eu-north-1:807414917081:function:tweetbrief
        run: |
          aws lambda update-function-code --function-name "${AWS_LAMBDA_FUNCTION_NAME}" --zip-file fileb://function.zip

      - name: Update configuration for AWS Lambda
        env:
          AWS_LAMBDA_FUNCTION_NAME: arn:aws:lambda:eu-north-1:807414917081:function:tweetbrief
          AWS_LAMBDA_LAYER_ARN: arn:aws:lambda:eu-north-1:807414917081:layer:dependencies
        run: |
          aws lambda update-function-configuration --function-name "${AWS_LAMBDA_FUNCTION_NAME}" --layers "${AWS_LAMBDA_LAYER_ARN}:${LAYER_VERSION}"