
name: CI/CD
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build \
            --file Dockerfile.aws \
            --tag tweetbrief-aws .
      
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          BRIEF_PERIOD: 1
          BRIEF_MAX_TWEETS: 32
          SINGLE_AUTHOR_MAX_TWEETS: 2
          URL2QR: True
        run: |
          docker run \
            --rm \
            --env AWS_ACCESS_KEY_ID \
            --env AWS_SECRET_ACCESS_KEY \
            --env AWS_DEFAULT_REGION \
            --env CONSUMER_KEY \
            --env CONSUMER_SECRET \
            --env DROPBOX_ACCESS_TOKEN \
            --env TARGET_USERNAME \
            --env BRIEF_PERIOD \
            --env BRIEF_MAX_TWEETS \
            --env SINGLE_AUTHOR_MAX_TWEETS \
            --env URL2QR \
            tweetbrief-aws
            